language: python
matrix:
  include:
    - name: "Python 3.8"
      dist: xenial
      python: "3.8"
    - name: "Python 3.7"
      dist: xenial
      python: "3.7"
    - name: "Python 3.6"
      dist: xenial
      python: "3.6"
services: postgresql
env: DATABASE_URL="postgres://postgres@localhost/dmp"
install: pip install -r requirements.txt
script: coverage run --source='music_publisher' --omit='music_publisher/migrations/*' manage.py test
after_success: coveralls

