language: python
python:
  - "3.7-dev"
  - "3.6"
  - "3.5"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U Django==$DJANGO_VERSION
# command to run tests
script:
  - coverage run --source='music_publisher' manage.py test 
after_success: coveralls
