language: python
matrix:
  include:
    - name: "Ubuntu 18.04"
      dist: bionic
    - name: "Ubuntu 16.04"
      dist: xenial
    - name: "Py3.6 PostgreSQL9.6"
      dist: precise
env: DATABASE_URL="postgres://postgres@localhost/dmp"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - coverage run --source='music_publisher' manage.py test 
after_success: coveralls
