language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
services:
  - postgresql
env:
  - DJANGO_VERSION=2.0.9
  - DJANGO_VERSION=2.1.2
  - DATABASE_URL="sqlite:///db.sqlite3"
  - DATABASE_URL="postgres://postgres@localhost/test_db"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U Django==$DJANGO_VERSION
# command to run tests
script:
  - coverage run --source='music_publisher' manage.py test 
after_success: coveralls
