language: python
matrix:
  include:
    - name: "18.04 Py3.8"
      dist: xenial
      python: "3.8"
    - name: "18.04 Py3.7"
      dist: xenial
      python: "3.7"
    - name: "16.04 Py3.6"
      dist: xenial
      python: "3.6"
    - name: "16.04 Py3.5"
      dist: xenial
      python: "3.5"
services: postgresql
env: DATABASE_URL="postgres://postgres@localhost/dmp"
install: pip install -r requirements.txt
script: coverage run --source='music_publisher' --omit='music_publisher/transactions/*' manage.py test
after_success: coveralls

