language: python
matrix:
  include:
    - name: "18.04 Py3.7 Pg10"
      dist: bionic
      python: "3.7"
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
    - name: "18.04 Py3.6 Pg10"
      dist: bionic
      python: "3.6"
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
    - name: "16.04 Py3.6"
      dist: xenial
      python: "3.6"
    - name: "16.04 Py3.5"
      dist: xenial
      python: "3.5"
services: postgresql
env: DATABASE_URL="postgres://postgres@localhost/dmp"
install: pip install -r requirements.txt
script: coverage run --source='music_publisher' --omit='music_publisher/migrations/*' manage.py test
after_success: coveralls

