language: python
matrix:
  include:
    - name: "Py3.7 Pg10"
      dist: xenial
      python: "3.7"
      addons:
        postgresql: "10"
        apt:
          packages:
          - postgresql-10
          - postgresql-client-10
    - name: "Py3.7"
      dist: xenial
      python: "3.7"
    - name: "Py3.6"
      dist: xenial
      python: "3.6"
    - name: "Py3.5"
      python: "3.5"
      dist: xenial
services:
  - postgresql
env: 
  - DATABASE_URL="postgres://postgres@localhost/dmp"
install:
  - pip install -r requirements.txt
script:
   - coverage run manage.py clearsessions
#    - coverage run --source='music_publisher' manage.py test
# after_success: coveralls

